### ISSUE TITLE
能实现多用户自动打新债吗

### ISSUE THREAD

**Issue by brotherbear2008** [lovehhf/auto_make_money#1]
可以实现多用户（我，爸，妈）自动打新债吗

**Comment by lovehhf** [comment]
> 可以实现多用户（我，爸，妈）自动打新债吗

可以，需要再同花顺委托页面同时登录3个账号， 再在 `config.py` 设置 `ACCOUNT_COUNT = 3`

**Comment by brotherbear2008** [comment]
> > 可以实现多用户（我，爸，妈）自动打新债吗
> 
> 可以，需要再同花顺委托页面同时登录3个账号， 再在 `config.py` 设置 `ACCOUNT_COUNT = 3`

**Comment by brotherbear2008** [comment]
有几个问题问一下
1. 客户端必须是windows pc？
2. python版本有要求吗
